name: "base:ffmpeg-rpi-alpine"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  ORG_NAME: ${{ github.repository_owner }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          echo "CURRENT_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      - name: Get current commit
        run: |
          echo "CURRENT_COMMIT=$(echo ${GITHUB_SHA} | head -c 7)" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: "Build.alpine.env|Build.alpine.rpi.env"
          export: "true"
          expandWithJobEnv: "true"
          expand: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/arm64, linux/arm/v7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Multi-Arch
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.alpine.rpi
          build-args: |
            BUILD_IMAGE=${{ env.OS_NAME }}:${{ env.OS_VERSION }}
            BUILD_DATE=${{ env.CURRENT_DATE }}
            BUILD_COMMIT=${{ env.CURRENT_COMMIT }}
            FFMPEG_VERSION=${{ env.FFMPEG_VERSION }}
          platforms: linux/arm64, linux/arm/v7
          push: true
          tags: |
            ghcr.io/guaclive/ffmpeg:${{ env.OS_NAME }}-ffmpeg-rpi-${{ env.OS_VERSION }}-${{ env.FFMPEG_VERSION }}
            ghcr.io/guaclive/ffmpeg:ffmpeg${{ env.FFMPEG_VERSION }}-rpi-${{ env.OS_NAME }}${{ env.OS_VERSION }}
