name: "base:ffmpeg-cuda-ubuntu"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  ORG_NAME: ${{ github.repository_owner }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          echo "CURRENT_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      - name: Get current commit
        run: |
          echo "CURRENT_COMMIT=$(echo ${GITHUB_SHA} | head -c 7)" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: "Build.ubuntu.env|Build.ubuntu.cuda.env"
          export: "true"
          expandWithJobEnv: "true"
          expand: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Multi-Arch
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.ubuntu.cuda
          build-args: |
            BUILD_IMAGE=nvidia/cuda:${{ env.CUDA_VERSION }}-devel-${{ env.OS_NAME }}${{ env.OS_VERSION }}
            BUILD_DATE=${{ env.CURRENT_DATE }}
            BUILD_COMMIT=${{ env.CURRENT_COMMIT }}
            DEPLOY_IMAGE=nvidia/cuda:${{ env.CUDA_VERSION }}-runtime-${{ env.OS_NAME }}${{ env.OS_VERSION }}
            FFNVCODEC_VERSION=${{ env.FFNVCODEC_VERSION }}
            FREETYPE_VERSION=${{ env.FREETYPE_VERSION }}
            XML2_VERSION=${{ env.XML2_VERSION }}
            SRT_VERSION=${{ env.SRT_VERSION }}
            X264_VERSION=${{ env.X264_VERSION }}
            X265_VERSION=${{ env.X265_VERSION }}
            VPX_VERSION=${{ env.VPX_VERSION }}
            LAME_VERSION=${{ env.LAME_VERSION }}
            OPUS_VERSION=${{ env.OPUS_VERSION }}
            OGG_VERSION=${{ env.OGG_VERSION }}
            VORBIS_VERSION=${{ env.VORBIS_VERSION }}
            DAV1D_VERSION=${{ env.DAV1D_VERSION }}
            RAV1E_VERSION=${{ env.RAV1E_VERSION }}
            FFMPEG_VERSION=${{ env.FFMPEG_VERSION }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/guaclive/ffmpeg:${{ env.OS_NAME }}-ffmpeg-cuda-${{ env.OS_VERSION }}-${{ env.FFMPEG_VERSION }}-${{env.CUDA_VERSION}}
            ghcr.io/guaclive/ffmpeg:ffmpeg${{ env.FFMPEG_VERSION }}-cuda-${{ env.OS_NAME }}${{ env.OS_VERSION }}-cuda${{env.CUDA_VERSION}}
